POST https://localhost:8080/user/register
Content-Type: application/json

{
    "username": "Vico",
    "password": "password",
    "email": "vicodrescher@web.de",
    "preference": "Python, Javascript, Java"
}
###
GET https://localhost:8080/user/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJpYXQiOjE2MjAyNDQyMjksImV4cCI6MTYyMTg2NDc3Mzc1N30.ZxHhkmTn_eKnVyh1PA4k371665-T09PUy0Sw96Z0SHg
###
POST https://localhost:8080/authenticate/tokenBasic HTTP/1.1
Content-Type: application/json

{
    "username": "Vico",
    "password": "password"
}
###

POST https://localhost:8080/authenticate/loginBasic
Authorization: Basic YWRtaW46MTIz

###
POST https://localhost:8080/user/forgot
Content-Type: application/json

{
    "email": "vicodrescher@web.de"
}

###
#Changing the password
POST https://localhost:8080/user/passwordReset/4bed1d889df208a525be31110badd7a3b4218faf
Content-Type: application/json

{
    "password" : "hund123"
}

#$2b$10$qN.u3qgyeqkhFT1r37Krfe3wJE0eW.Hhu1zofP2UPNgQeZDCkyVoi