
#Get all user objects
GET https://localhost:8080/user/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJpYXQiOjE2MjAyNDQyMjksImV4cCI6MTYyMTg2NDc3Mzc1N30.ZxHhkmTn_eKnVyh1PA4k371665-T09PUy0Sw96Z0SHg
###
#Register a new user object
POST https://localhost:8080/user/register
Content-Type: application/json

{
    "username": "tati",
    "password": "coins",
    "email": "test@testmail.com",
    "preference": "Python, Javascript, Java"
}
###
#Get specific user object with id
GET https://localhost:8080/user/60ac162ae61f7d2ea071fa44
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJpYXQiOjE2MjAyNDQyMjksImV4cCI6MTYyMTg2NDc3Mzc1N30.ZxHhkmTn_eKnVyh1PA4k371665-T09PUy0Sw96Z0SHg
###
#Update specific user object with id
PATCH https://localhost:8080/user/60ac162ae61f7d2ea071fa44
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJpYXQiOjE2MjAyNDQyMjksImV4cCI6MTYyMTg2NDc3Mzc1N30.ZxHhkmTn_eKnVyh1PA4k371665-T09PUy0Sw96Z0SHg
Content-Type: application/json

{
    "username": "WowneuerUser",
    "password": "passwordneu",
    "email": "Neue@testmail.com",
    "preference": "Python, Javascript, Java"
}
###
#Delete specific user object with id
DELETE https://localhost:8080/user/60ac162ae61f7d2ea071fa44
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJpYXQiOjE2MjAyNDQyMjksImV4cCI6MTYyMTg2NDc3Mzc1N30.ZxHhkmTn_eKnVyh1PA4k371665-T09PUy0Sw96Z0SHg

###
#Get BasicToken of other User
POST https://localhost:8080/authenticate/tokenBasic HTTP/1.1
Content-Type: application/json

{
    "username": "Badibu",
    "password": "katze"
}
###
#Login as User
POST https://localhost:8080/authenticate/loginBasic
Authorization: Basic QmFkaWJ1OmthdHpl

###
#Login as Admin
POST https://localhost:8080/authenticate/loginBasic
Authorization: Basic YWRtaW46MTIz

###
#Get user by username
GET https://localhost:8080/user/find/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJpYXQiOjE2MjAyNDQyMjksImV4cCI6MTYyMTg2NDc3Mzc1N30.ZxHhkmTn_eKnVyh1PA4k371665-T09PUy0Sw96Z0SHg

###
#Check if user is admin
GET https://localhost:8080/user/admin/isadmin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJpYXQiOjE2MjAyNDQyMjksImV4cCI6MTYyMTg2NDc3Mzc1N30.ZxHhkmTn_eKnVyh1PA4k371665-T09PUy0Sw96Z0SHg

###
#Check if user is admin
GET https://localhost:8080/user/admin/isadmin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiQmFkaWJ1IiwiaWF0IjoxNjI1MzE3MzU4LCJleHAiOjE2MjY5NDI5NzU1OTN9.WR77QOUK0ntGjbTvNVA24Z-6DJhf4p2WAxgM_r6262M